---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mon
  name: grafana-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
